language: elixir

elixir:
  - 1.5.1

otp_release:
  - 20.1

env:
  global:
    - MIX_ENV=test

notifications:
  - email: false
  - slack: altumhq:iIGyoyfNXDRP7hvem5Zney6h

sudo: false

script:
  - mix test  
  - mix coveralls.travis
